In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.arima_model import ARIMA
from statsmodels.tsa.stattools import adfuller
import statsmodels.api as sm
from pandas.tseries.offsets import DateOffset

# csv_import = 'State_Zhvi_1bedroom.csv'
# csv_import = 'State_Zhvi_2bedroom.csv'
# csv_import = 'State_Zhvi_3bedroom.csv'
# csv_import = 'State_Zhvi_4bedroom.csv'
csv_import = 'State_Zhvi_5BedroomOrMore.csv'
# csv_import = 'State_Zhvi_AllHomes.csv'
data = pd.read_csv(csv_import, header = None)
data_refined = data.iloc[:,5:]
state_list = data_refined[5].tolist()[1:]

data_refined = data.iloc[:,6:].T

df = data_refined.rename(columns = {0: "Date"})

for index, state in enumerate(state_list):
    df.rename(columns = {index+1 : state}, inplace = True)
    
df["CA"] = pd.to_numeric(df["CA"])
df["Date"] = pd.to_datetime(df["Date"])
df.set_index("Date", inplace = True)
model = sm.tsa.statespace.SARIMAX(df["CA"], order=(1, 1, 1), seasonal_order=(1,1,1,12))
model_fit = model.fit()
model_fit.summary()
future_dates = [df.index[-1] + DateOffset(months = x) for x in range(0,60)]
future_datest_df = pd.DataFrame(index = future_dates[1:], columns = df.columns)
future_df = pd.concat([df,future_datest_df])
future_df['CA_forecast'] = model_fit.predict(start = 291, end = 351, dynamic = True)

for state in state_list[1:]:

    df[state] = pd.to_numeric(df[state])
    model = sm.tsa.statespace.SARIMAX(df[state], order=(1, 1, 1), seasonal_order=(1,1,1,12))
    model_fit = model.fit()
    model_fit.summary()
    future_df[state + "_forecast"] = model_fit.predict(start = 291, end = 351, dynamic = True)  
#     future_df[['Values', 'forecast']].plot(figsize=(12, 8))

future_df.to_csv("forecast_" + csv_import)

C:\Users\sjhkm\anaconda3\envs\py37\lib\site-packages\statsmodels\tsa\base\tsa_model.py:527: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
C:\Users\sjhkm\anaconda3\envs\py37\lib\site-packages\statsmodels\tsa\base\tsa_model.py:527: ValueWarning: No frequency information was provided, so inferred frequency M will be used.
  % freq, ValueWarning)
C:\Users\sjhkm\anaconda3\envs\py37\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py:2937: RuntimeWarning: divide by zero encountered in true_divide
  return self.params / self.bse
C:\Users\sjhkm\anaconda3\envs\py37\lib\site-packages\statsmodels\tsa\statespace\mlemodel.py:3108: RuntimeWarning: invalid value encountered in double_scalars
  test_statistic = np.sum(numer_resid) / np.sum(denom_resid)
C:\Users\sjhkm\anaconda3\envs\py37\lib\site-packages\statsmodels\tsa\stattools.py:672: RuntimeWarning: invalid value encountered in true_divide
  acf = avf[: nlags + 1] / avf[0]

,CA,TX,NY,FL,IL,PA,OH,MI,GA,NC,...,RI,MT,DE,SD,AK,ND,VT,DC,WY,NC_forecast
1996-01-31,262515.0,232679.0,204713.0,213181.0,258152.0,161662.0,169684.0,156607.0,206036.0,233596.0,...,204040.0,NaN,217036.0,130392.0,205871.0,NaN,137659.0,378860.0,NaN,NaN
1996-02-29,262347.0,232574.0,204163.0,213236.0,257530.0,161470.0,169812.0,157030.0,206311.0,234292.0,...,204350.0,NaN,216679.0,130125.0,206491.0,NaN,137574.0,378312.0,NaN,NaN
1996-03-31,262147.0,232547.0,203767.0,213350.0,256821.0,161274.0,169948.0,157418.0,206559.0,234824.0,...,204337.0,NaN,216376.0,129364.0,206639.0,NaN,137396.0,377619.0,NaN,NaN
1996-04-30,261866.0,232580.0,203106.0,213504.0,255807.0,160955.0,170239.0,158349.0,207104.0,235810.0,...,204308.0,NaN,215905.0,128369.0,208171.0,NaN,137172.0,376364.0,NaN,NaN
1996-05-31,261629.0,232670.0,202731.0,213667.0,254503.0,160710.0,170536.0,159262.0,207634.0,236666.0,...,203985.0,NaN,216029.0,127807.0,209409.0,NaN,136975.0,374814.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.541578e+10
2024-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.554728e+10
2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.567879e+10
2025-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.581484e+10
2025-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.595363e+10